# Generated by Django 4.2.11 on 2026-04-16 19:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sellers", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("fixed", "Fixed Amount"), ("percent", "Percentage")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                ("times_used", models.PositiveIntegerField(default=0)),
                (
                    "seller_restricted",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this coupon only applies to products from this seller.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "coupons",
                "ordering": ["-valid_from"],
            },
        ),
    ]
