# Generated by Django 4.2.11 on 2026-05-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_2fa_enabled_user_otp_secret"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="otp_secret",
            new_name="totp_secret",
        ),
    ]
