# Generated by Django 4.2.11 on 2026-04-15 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricehistory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_history",
                to="products.product",
            ),
        ),
    ]
