# Generated by Django 4.2.11 on 2026-04-15 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pricing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricealert",
            name="buyer",
            field=models.ForeignKey(
                limit_choices_to={"role": "buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pricealert",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_alerts",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["product", "-recorded_at"],
                name="price_histo_product_6f9c57_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricealert",
            index=models.Index(
                fields=["buyer", "status"], name="price_alert_buyer_i_49cdcd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricealert",
            unique_together={("buyer", "product")},
        ),
    ]
