# Generated by Django 4.2.11 on 2026-05-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="commission_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
