# Generated by Django 4.2.11 on 2026-05-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0003_sellerprofile_commission_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="seller_banners/"),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="country",
            field=models.CharField(default="US", max_length=100),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="seller_logos/"),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
