# Generated by Django 4.2.11 on 2026-04-15 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="buyer",
            field=models.OneToOneField(
                limit_choices_to={"role": "buyer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
