# Generated by Django 4.2.11 on 2026-04-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_applied",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="promotions.coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
