# Generated by Django 4.2.11 on 2026-05-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_carrier_order_shipping_rate_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="commission_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="seller_earnings",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
