# Generated by Django 5.2.13 on 2026-04-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery_days",
            field=models.PositiveIntegerField(
                default=3, help_text="Estimated shipping days"
            ),
        ),
    ]
