# Generated by Django 4.2.11 on 2026-05-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_category_image_product_clicks_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="clicks_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
