# Generated by Django 4.2.11 on 2026-05-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_clicks_count_product_views_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="SKU",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, unique=True
            ),
        ),
    ]
